Bootstrap: docker
From: quay.io/fenicsproject/stable:current

%post
    ldconfig

%files
    WELCOME.Singularity /usr/local/share/WELCOME

%runscript
    cat /usr/local/share/WELCOME 
    exec /bin/bash -i
